### ISSUE TITLE
Issue: Negative Numbers Accepted in Weight Input

### ISSUE THREAD

**Issue by mong00x** [Hachondeoro/fitness-playground#3]
**Description**
The UserInput component currently allows negative numbers to be entered for Weight . This can lead to invalid data being stored and used within the application.

**Steps to Reproduce**
Navigate to the the Home page.
Enter a negative number in Weight input field.
Observe that the negative number is accepted and stored.

**Expected Behavior**
The input fields for Weight should only accept non-negative numbers.

**Actual Behavior**
Negative numbers are accepted and stored in the state.

**Affected Code**
The issue is present in the UserInput component, specifically in the input handler for Weight .

**Proposed Solution**
Add validation logic to the input handlers to ensure only non-negative numbers are accepted.

**Comment by Hachondeoro** [comment]
Sure, please submit a pull request
